### ISSUE TITLE
Fix dead links

### ISSUE THREAD

**Issue by Epictek** [FreesideHullUni/StudentResources#1]
Link to the tutorial on how to contribute now 404's, Here is an archive of it. Should probably rewrite it as a markdown file as the original content is not creative commons (that I know of)
http://web.archive.org/web/20220328053958/https://love.edwardcharl.es/contributing-to-the-freeside-srl/

**Comment by CrimsonTome** [comment]
Thank you, I'll look into reimplementing this, even if it has to be adapted if we're not to use @closebracket 's content. The SRL itself is under a license where we don't have to remove content.

**Comment by CrimsonTome** [comment]
Will now close this issue as we have the original organisation back, a new how to contribute will eventually be made for that.
